version: '3.7'

services:
  cache:
    container_name: cache
    image: redislabs/redismod:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
       - ./data:/data
  cron:
    build:
      context: ./crontab
    env_file:
        ./.env
    ports:
      - "5000:5000"
    depends_on:
      - cache
    links:
      - cache

  api:
    build:
      context: ./api
    env_file:
        ./.env
    ports:
      - "8000:8000"
    depends_on:
      - cache
      - cron
    links:
      - cache
    healthcheck:
      test: curl -f http://localhost:8000/healthcheck
      interval: 3s
      timeout: 30s
      retries: 90

  
volumes:
  cache:
    driver: local