version: '3.8'

services:
  cache:
    image: redislabs/redismod:latest
    restart: always
    ports:
      - '6379:6379'
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    # volumes: 
    #   - cache:/data
    networks:
      - mspr

  cron:
    build:
      context: ./crontab
    env_file:
        "./.env"
    ports:
      - "5000:5000"
    networks:
      - mspr
    depends_on:
      - cache  
  
  api:
    build:
      context: ./api
    env_file:
        "./.env"
    ports:
      - "8000:8000"
    networks:
      - mspr
    depends_on:
      - cron
    healthcheck:
      test: curl -f http://localhost:8000/healthcheck
      interval: 3s
      timeout: 30s
      retries: 90

  
volumes:
  cache:
    driver: local

networks:
  mspr:
    external:
      name: mspr