export const MTP_PARKING = {
    "Antigone": "FR_MTP_ANTI",
    "Comédie": "FR_MTP_COME",
    "Corum": "FR_MTP_CORU",
    "Europa": "FR_MTP_EURO",
    "Foch": "FR_MTP_FOCH",
    "Gambetta": "FR_MTP_GAMB",
    "Gare" :"FR_MTP_GARE",
    "Triangle": "FR_MTP_TRIA",
    "Arc de Triomphe": "FR_MTP_ARCT",
    "Pitot" :"FR_MTP_PITO",
    "Circe" :"FR_MTP_CIRC",
    "Sabines" :"FR_MTP_SABI",
    "Garcia Lorca" :"FR_MTP_GARC",
    "Sablassou" :"FR_CAS_SABL",
    "Mosson" :"FR_MTP_MOSS",
    "Saint Jean Le Sec" :"FR_STJ_SJLC",
    "Euromédecine" :"FR_MTP_MEDC",
    "Occitanie" :"FR_MTP_OCCI",
    "Vicarello" :"FR_CAS_VICA",
    "Gaumont EST" :"FR_MTP_GA109",
    "Gaumont OUEST" :"FR_MTP_GA250",
    "Charles de Gaulle" :"FR_CAS_CDGA",
    "Arceaux" :"FR_MTP_ARCE",
    "Polygone" :"FR_MTP_POLY",
};